# title of website
title: 跨境选品导航

# description of website
description: 跨境选品导航

# favicon of website
favicon: "https://github.com/linfox.png?size=40"

# your website url
url: https://linfox.github.io/kuajing

# github profile url
github: "https://github.com/linfox"

# footer message
footer: © 2021-2021 @linfox

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: 亚马逊TOP 25W搜索词
          description: AMZ出品，每周更新
          url: https://www.amz123.com/usatopkeywords
        - name: 雨果网
          description: 
          url: https://www.cifnews.com/
        - name: Globalsources Analyst's Choice
          description: 
          url: https://www.globalsources.com/product/landingPage/analystChoice?source=GSOLHP_AC_SeeAll
        - name: Globalsources New Product
          description: 
          url: https://www.globalsources.com/product/list?source=GSOLHP_NewProd_ViewMore
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        
    - name: 众筹
      sites:
        - name: Kickstarter Product Design
          description: 
          url: https://www.kickstarter.com/discover/advanced?category_id=28&ref=section-design-tech-explore-module&sort=magic
        - name: Indiegogo
          description: 
          url: https://www.indiegogo.com/
        - name: Pozible
          description: 
          url: https://www.pozible.com/
        - name: 啧啧
          description: 
          url: https://www.zeczec.com/
    - name: 硬件资讯
      sites:
        - name: Engadget
          description: 
          url: https://www.engadget.com/
        - name: Lifehacker
          description: 
          url: https://lifehacker.com/
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
    - name: 趣味礼品
      sites:
        - name: 趣玩网
          description: 
          url: https://www.quwan.com/
        - name: Fancy
          description: 
          url: https://fancy.com/
        - name: 爱范儿玩物志
          description: 
          url: https://www.ifanr.com/coolbuy
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
       
    - name: 工业设计
      sites:
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
       
    - name: 独立站大卖新品
      sites:
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
     
    - name: 各国购物站点
      sites:
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
      
    - name: 上游供应链
      sites:
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        
    - name: 专业选品工具
      sites:
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
      
   
    - name: 技术玩法
      sites:
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        
