# title of website
title: 跨境选品导航

# description of website
description: 只关注新品

# favicon of website
favicon: "https://github.com/linfox.png?size=40"

# your website url
url: https://linfox.github.io/kuajing

# footer message
footer: © 2021-2021 @linfox

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: 亚马逊TOP 25W搜索词
          description: AMZ出品，每周更新
          url: https://www.amz123.com/usatopkeywords
        - name: 雨果网
          description: 
          url: https://www.cifnews.com/
        - name: Globalsources Analyst's Choice
          description: 
          url: https://www.globalsources.com/product/landingPage/analystChoice?source=GSOLHP_AC_SeeAll
        - name: Globalsources New Product
          description: 
          url: https://www.globalsources.com/product/list?source=GSOLHP_NewProd_ViewMore
        - name: 1688
          description: 
          url: https://www.1688.com/
          
     
        
    - name: 众筹
      sites:
        - name: Kickstarter Product Design
          description: 
          url: https://www.kickstarter.com/discover/advanced?category_id=28&ref=section-design-tech-explore-module&sort=magic
        - name: Indiegogo
          description: 
          url: https://www.indiegogo.com/
        - name: Pozible
          description: 
          url: https://www.pozible.com/
        - name: 啧啧
          description: 
          url: https://www.zeczec.com/
    - name: 新闻资讯
      sites:
        - name: Engadget
          description: 
          url: https://www.engadget.com/
        - name: Lifehacker
          description: 
          url: https://lifehacker.com/
        - name: Product Hunt
          description: 专业新品捕捉，软件类为主，硬件也有
          url: https://www.producthunt.com/
        - name: 雷锋网
          description: 
          url: https://www.leiphone.com/
        - name: IT桔子
          description: 各种公司品牌的融资信息
          url: https://www.itjuzi.com/
    - name: 趣味礼品
      sites:
        - name: 趣玩网
          description: 
          url: https://www.quwan.com/
        - name: Fancy
          description: 
          url: https://fancy.com/
        - name: 爱范儿玩物志
          description: 
          url: https://www.ifanr.com/coolbuy
        - name: 博派创意礼品小铺
          description: 
          url: http://i.biopatent.cn/
        - name: 爱稀奇
          description: 
          url: http://www.ixiqi.com/
       
    - name: 工业设计
      sites:
        - name: Pinterest
          description: 
          url: https://www.pinterest.com/
        - name: Billwang 工业设计
          description: 
          url: http://www.billwang.net/
        - name: 普象网
          description: 
          url: https://www.puxiang.com/
        - name: Behance
          description: 
          url: https://www.behance.net/
        - name: Yanko
          description: 
          url: https://www.yankodesign.com/
       
    - name: 独立站大卖新品
      sites:
        - name: Gearbest New
          description: 
          url: https://www.gearbest.com/new-products/
        - name: Sunsky New
          description: 
          url: https://www.sunsky-online.com/marketing/promotion!newArrivals.do
        - name: Banggood Top
          description: 
          url: https://www.banggood.com/ranking.html?bid=56273&from=nav
        - name: Tomtop New
          description: 
          url: https://www.tomtop.com/new-arrivals/
        
     
    - name: 各国购物站点
      sites:
        - name: Naver Shopping
          description: 
          url: https://shopping.naver.com/home/p/index.naver
        - name: Coupang
          description: 
          url: https://www.coupang.com/
        - name: Gmarket
          description: 
          url: https://www.gmarket.co.kr/
        
      
    - name: 上游供应链
      sites:
        - name: 充电头网
          description: 
          url: https://www.chongdiantou.com/
        - name: 未来工场
          description: 3D打印服务；拖入图纸，系统自动报价
          url: https://www.wenext.cn/
        - name: 嘉立创
          description: 小批量PCB服务
          url: https://www.jlc.com/
        - name: 硬蛋网
          description: IC商城
          url: https://www.ingdan.com/
        - name: 我爱方案网
          description: 方案超市
          url: https://www.52solution.com/
        
    - name: 专业选品工具
      sites:
        - name: Amzscout
          description: 
          url: https://amzscout.net/
        - name: Junglescout
          description: 
          url: https://www.junglescout.com/
        - name: 卖家精灵
          description: 
          url: https://www.sellersprite.com/
        - name: CamelCamelCamel
          description: 
          url: https://camelcamelcamel.com/
        - name: 紫鸟数据
          description: 
          url: https://www.ziniao.com/
      
   
    - name: 技术玩法
      sites:
        - name: Google New Bluetooth Speaker
          description: 替换关键词可查其他新品
          url: https://www.google.com/search?q=bluetooth+speaker&newwindow=1&hl=zh-CN&biw=1718&bih=1283&tbm=nws&sxsrf=APq-WBuXmQL6BFLPIEbWzbWCYvpQHUpxxg%3A1646122757171&ei=BdcdYuz0CeqxrgT28LHoCA&ved=0ahUKEwisi8qRvaT2AhXqmIsKHXZ4DI0Q4dUDCA0&uact=5&oq=bluetooth+speaker&gs_lcp=Cgxnd3Mtd2l6LW5ld3MQAzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQ6BwgAEIAEEAo6BAgAEENQAFjXO2CGPmgAcAB4AIAB_gKIAfkqkgEEMy0xNpgBAKABAcABAQ&sclient=gws-wiz-news
        - name: Google New Power Bank
          description: 替换关键词可查其他新品
          url: https://www.google.com/search?q=power+bank&newwindow=1&hl=zh-CN&biw=1718&bih=1283&tbm=nws&sxsrf=APq-WBv6CUyzuAT79fn9tc_-PuQgvKVE4g%3A1646743351539&ei=N08nYpzFIJXL0PEPwpCNQA&ved=0ahUKEwjcvISExbb2AhWVJTQIHUJIAwgQ4dUDCA0&uact=5&oq=power+bank&gs_lcp=Cgxnd3Mtd2l6LW5ld3MQAzIECAAQQzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDoGCAAQChBDOgcIABCABBAKUABYzwtgig5oAHAAeACAAa4FiAH4G5IBCTItNi4xLjEuMpgBAKABAcABAQ&sclient=gws-wiz-news
        - name: Google New phone stand
          description: 替换关键词可查其他新品
          url: https://www.google.com/search?q=phone+stand&newwindow=1&hl=zh-CN&biw=1718&bih=1283&tbm=nws&sxsrf=APq-WBu85COkifuPJNGem_jmHgp7_v_sig%3A1646743355709&ei=O08nYpfoKtXW9APw74mwBw&ved=0ahUKEwjX8YKGxbb2AhVVK30KHfB3AnYQ4dUDCA4&uact=5&oq=phone+stand&gs_lcp=Cgxnd3Mtd2l6LW5ld3MQAzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQ6BAgAEEM6BwgAEIAEEAo6CQgAEIAEEAwQClAAWMweYNMgaARwAHgBgAHAA4gB0CKSAQcyLTYuNy4xmAEAoAEBsAEAwAEB&sclient=gws-wiz-news
        - name: Google New bluetooth earbud
          description: 替换关键词可查其他新品
          url: https://www.google.com/search?q=bluetooth+earbud&newwindow=1&hl=zh-CN&biw=1718&bih=1283&tbm=nws&sxsrf=APq-WBvkjyAYs5dRTv-PkjuVg_e8Wx6RxQ%3A1646743472186&ei=sE8nYvbjCtPO0PEPtKunqAw&ved=0ahUKEwj2-8e9xbb2AhVTJzQIHbTVCcUQ4dUDCA0&uact=5&oq=bluetooth+earbud&gs_lcp=Cgxnd3Mtd2l6LW5ld3MQAzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQ6BAgAEEM6BwgAEIAEEApQ4QVY-RJghRtoAHAAeACAAbcCiAG0E5IBBTItOC4xmAEAoAEBwAEB&sclient=gws-wiz-news
        
        
